AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/ClassAndModuleChildren:
  Enabled: true
  EnforcedStyle: compact

Style/RedundantSelf:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 20
